In [1]:
import pandas as pd

In [3]:
info  = {
    "Name" : ["Rahul" , "Harshita", "Shraddha"],
    "CGPA" : [9.5, 7.5, 8.5]
}

df = pd.DataFrame(info)

print(df)

       Name  CGPA
0     Rahul   9.5
1  Harshita   7.5
2  Shraddha   8.5

In [4]:
df

       Name  CGPA
0     Rahul   9.5
1  Harshita   7.5
2  Shraddha   8.5

In [6]:
#Series
s = pd.Series([1,2,3,4,5])
print(s)

#index
print(s[0])

0    1
1    2
2    3
3    4
4    5
dtype: int64
1

In [10]:
s = pd.Series([23,24,25,26], index= ["Adam", "eve", "bob", "charlie"])
print(s)

print(s["Adam"]) #Label based Access
print(s[0]) #index based access
s.index

Adam       23
eve        24
bob        25
charlie    26
dtype: int64
23
23

D:\Temp\ipykernel_14212\3169684897.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[0]) #index based access

Index(['Adam', 'eve', 'bob', 'charlie'], dtype='object')

In [16]:
s1 = pd.Series([1,2,3])
s2 = pd.Series([1,2,3])

s3 = s1 + s2
s3

s1[0] = 100
changed_s1 = s1.drop(0)
print(s1)
print(changed_s1)

0    100
1      2
2      3
dtype: int64
1    2
2    3
dtype: int64

In [20]:
#DataFrame

info= {

    "Name" : ["Adam" , "Eve" , "Bob"],
    "Age" : [23,24,25],
    "CGPA" : [9.6,8.5, 7.8]
}

df = pd.DataFrame(info)
print(df)
print(df.index)
print(df.columns)

   Name  Age  CGPA
0  Adam   23   9.6
1   Eve   24   8.5
2   Bob   25   7.8
RangeIndex(start=0, stop=3, step=1)
Index(['Name', 'Age', 'CGPA'], dtype='object')

In [18]:
df

   Name  Age  CGPA
0  Adam   23   9.6
1   Eve   24   8.5
2   Bob   25   7.8

In [24]:
#DataFrame using lists

df = pd.DataFrame([["Adam", 23] , ["Eve", 24] , ["Bob",25]], columns = ["Name" , "Age"])
print(df)

   Name  Age
0  Adam   23
1   Eve   24
2   Bob   25

In [26]:
#DataFrame using numPy array

import numpy as np

np_arr = np.array([[1,2,3], [4,5,6]])

df = pd.DataFrame(np_arr , columns = ["A", "B", "C"])

df

   A  B  C
0  1  2  3
1  4  5  6

In [27]:
# cvs data

df = pd.read_csv("employee_data.csv")
print(df, type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.core.frame.DataFrame'>

In [29]:
# json data

df  = pd.read_json("employee_data.json")

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [37]:
#Methods

df.head() #starting 5 values by default

df.tail(2)

df.sample(5)

df.info()

df.shape

df.describe()

df.nunique()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     object
 2   Age         10 non-null     int64
 3   Department  10 non-null     object
 4   Salary      10 non-null     int64
dtypes: int64(3), object(2)
memory usage: 532.0+ bytes

ID            10
Name          10
Age           10
Department     4
Salary        10
dtype: int64

In [36]:
df

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [40]:
# AQI DATASET

df = pd.read_csv("globalAirQuality.csv")

df.head()
df.describe()

,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
count,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000
mean,23.065980,37.655560,40.369131,70.152228,32.055176,6.035508,48.065100,0.800595,104.645556,21.510251,57.714351,5.283910
std,26.156536,78.600701,17.647450,24.999440,13.820680,2.454790,14.950849,0.250254,25.616070,9.509444,18.844908,2.741712
min,-37.814000,-123.121000,0.025000,0.061000,0.013000,0.003000,0.114000,0.000000,16.000000,5.000000,25.002000,0.500000
25%,12.972000,2.352000,27.904500,53.125500,22.362500,4.360750,38.028500,0.633000,87.000000,13.357750,41.320000,2.937000
50%,29.232000,42.146000,40.286500,69.961000,32.019500,6.026000,48.142000,0.800500,103.000000,21.455500,57.847000,5.297000
75%,41.008000,103.820000,52.436250,87.256500,41.364250,7.715250,58.258500,0.969000,121.000000,29.688250,74.234750,7.662000
max,60.170000,174.763000,115.683000,161.810000,90.019000,16.559000,103.016000,1.832000,231.000000,37.998000,89.997000,9.999000

In [46]:
#Selecting the Data\

#column selection
df["city"]
df[["city", "aqi"]]


#Row selection
df.loc[0]
df.loc[0:2]   # start dx : end index(inclusive)

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650